stages:
  - deploy

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=gallery-django --api-key=8747ebca-6761-46b7-bf5d-7876529a4f9f
    - heroku stack:set container
    - git push heroku master
    # - heroku container:push web --context-path ../
    # - heroku container:release web
    # - export HEROKU_API_KEY=$HEROKU_APIKEY
    # - heroku run --app $HEROKU_APPNAME python manage.py migrate
  environment:
    name: production
    url: https://gallery-django.herokuapp.com