stages:
  - deploy

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - export $HEROKU_APP_PRODUCTION
    - export $HEROKU_API_KEY
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    # - heroku container:push web --context-path ../
    # - heroku container:release web
  environment:
    name: production
    # url: https://gallery-django.herokuapp.com