stages:
  - build
  - release

build_image:
  only:
    - master
  stage: build
  variables:
  before_script:
    - curl https://cli-assets.heroku.com/install.sh | sh
    - sed -i '/^mountopt =.*/d' /etc/containers/storage.conf
  script:
    - buildah bud --iidfile iidfile -t rust-python-demo:$CI_COMMIT_SHORT_SHA .
    - buildah push --creds=_:$(heroku auth:8747ebca-6761-46b7-bf5d-7876529a4f9f) $(cat iidfile) registry.heroku.com/gallery-django /web

release:
  only:
    - master
  stage: release
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release -a gallery-django web