image: python:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - deployment

staging:
    stage: deployment
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=gallery-django --api-key=8747ebca-6761-46b7-bf5d-7876529a4f9f
        - python src/manage.py migrate && \
        - python src/manage.py collectstatic --noinput && \
        - cd src && \
        - gunicorn gallery.wsgi:application --bind 0.0.0.0:$PORT