stages:
  - deploy

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=gallery-django --api-key=8747ebca-6761-46b7-bf5d-7876529a4f9f
    - heroku stack:set heroku-20 -a=gallery-django
    - heroku container:push web --context-path ../
    - heroku container:release web
  environment:
    name: production
    url: https://gallery-django.herokuapp.com