stages:
 - package
 - deploy


build_image:
  image: docker:latest
  services:
  - docker:dind
  stage: package
  script:
    - docker login -u gitlab-ci-token -p JoVQuem8yXenC2axX1V- registry.gitlab.com
    - docker build -t registry.gitlab.com/maciejsobala/gallery-django .
    - docker push registry.gitlab.com/akostyukov/gallery-django:latest

deploy_to_heroku:
  stage: deploy
  services:
  - docker:dind
  script:
    - docker login --email=_ --username=_ --password=8747ebca-6761-46b7-bf5d-7876529a4f9f registry.heroku.com
    - docker tag registry.gitlab.com/akostyukov/gallery-django:latest registry.heroku.com/akostyukov/gallery-django:latest
    - docker push registry.heroku.com/akostyukov/gallery-django:latest