version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: bash -c "python src/manage.py migrate &&
              python src/manage.py collectstatic --noinput &&
              cd src/ &&
              gunicorn gallery.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - static_volume:/gallery/src/static
      - media_volume:/gallery/src/media
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/gallery/src/static
      - media_volume:/gallery/src/media
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: